version: "3.1"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    command: "php -S 0.0.0.0:8080 -t public"
  db:
    image: "mariadb:10.6"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_store/:/var/lib/mysql/
    environment:
      MARIADB_DATABASE: store
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: localuser
      MARIADB_PASSWORD: secret
